### ISSUE TITLE
Alertmanager timeout inaccessible in prometheus config

### ISSUE THREAD

**Issue by cmwylie19** [RHEcosystemAppEng/monitoring-stack-operator#5]
The prometheus configuration exposes a timeout field for the `alertmanagers` array:

```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring-stack-operator/starburst
    prometheus_replica: prometheus-starburst-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    scheme: http
    path_prefix: /
    timeout: 10s # Here
 ```
 
 Through the prometheus operator, you would configure the timeout field in the prometheus instance:
 ```
 spec:
  additionalScrapeConfigs:
    key: self-scrape-config
    name: starburst-prometheus-additional-scrape-configs
  alerting:
    alertmanagers:
    - apiVersion: v2
      name: starburst-alertmanager
      namespace: monitoring-stack-operator
      timeout: 2s # Timeout
      port: web
      scheme: http
```

This is overwritten by the MSO which changes the prometheus instance back.

We would need to expose the Prometheus timeout from the instance of the MSO operator to update the timeout.
